version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "master"
    update_schedule: "daily"
    ignored_updates:
    #   - match:
    #       # Ignore k8s.io dependencies which aren't 0.16.x
    #       dependency_name: "k8s.io/*"
    #       version_requirement: ">=0.17.0"
    #   - match:
    #       # Ignore k8s.io dependencies which aren't 0.16.x
    #       dependency_name: |
    #         k8s\.io\/*
    #       version_requirement: ">=0.17.0"
    #   - match:
    #       # Ignore k8s.io dependencies which aren't 0.16.x
    #       dependency_name: >
    #         k8s\.io\/.*
    #       version_requirement: ">=0.17.0"
    #   - match:
    #       # Ignore k8s.io dependencies which aren't 0.16.x
    #       dependency_name: >
    #         k8s\.io\/.**
    #       version_requirement: ">=0.17.0"
    #   - match:
    #       # Ignore k8s.io dependencies which aren't 0.16.x
    #       dependency_name: "k8s.io/**"
    #       version_requirement: ">=0.17.0"
    #   - match:
    #       # Ignore k8s.io dependencies which aren't 0.16.x
    #       dependency_name: 'k8s\.io\/**'
    #       version_requirement: ">=0.17.0"
    #   - match:
    #       # Ignore k8s.io dependencies which aren't 0.16.x
    #       dependency_name: 'k8s\.io\/.**'
    #       version_requirement: ">=0.17.0"
    #   - match:
    #       # Ignore k8s.io dependencies which aren't 0.16.x
    #       dependency_name: 'k8s\.io\/.*\/*.*'
    #       version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: 'k8s.io/...'
          version_requirement: ">=0.17.0"
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "all-rules"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: "k8s.io/*"
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: |
            k8s\.io\/*
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: >
            k8s\.io\/.*
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: >
            k8s\.io\/.**
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: "k8s.io/**"
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: 'k8s\.io\/**'
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: 'k8s\.io\/.**'
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: 'k8s\.io\/.*\/*.*'
          version_requirement: ">=0.17.0"
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "1-half-rules"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: "k8s.io/*"
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: |
              k8s\.io\/*
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: 'k8s\.io\/.**'
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: 'k8s\.io\/.*\/*.*'
          version_requirement: ">=0.17.0"
  - package_manager: "go:modules"
    directory: "/"
    target_branch: "2-half-rules"
    update_schedule: "daily"
    ignored_updates:
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: >
              k8s\.io\/.*
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: >
              k8s\.io\/.**
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: "k8s.io/**"
          version_requirement: ">=0.17.0"
      - match:
          # Ignore k8s.io dependencies which aren't 0.16.x
          dependency_name: 'k8s\.io\/**'
          version_requirement: ">=0.17.0"
